version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: market_data_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: market_data_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: